"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { AppShell } from "@/components/app/app-shell";
import { RequireAuth } from "@/features/auth/require-auth";
import { useAuth } from "@/features/auth/auth-context";
import { PageHeading, formatDate } from "@/components/tickets/ticket-ui";
import { Card } from "@/components/ui/card";
import { Drawer } from "@/components/ui/drawer";
import { useToast } from "@/components/ui/toast";
import { SlaBadge } from "@/components/sla/sla-panel";
import { priorities, priorityLabels, type TicketPriority } from "@/features/tickets/types";
import { slaService } from "@/services/sla/service";
import { resultLabels, type CycleEvaluation, type PolicyInput, type SlaPolicyVersion } from "@/services/sla/types";
const initial: PolicyInput = { productId: "product-commander", priority: "MEDIUM", firstResponseMinutes: 120, resolutionMinutes: 1440, pauseResolutionWhileWaitingCustomer: true };
function Policies() {
  const { products } = useAuth(); const { notify } = useToast();
  const [policies, setPolicies] = useState<SlaPolicyVersion[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false); const [input, setInput] = useState(initial); const [busy, setBusy] = useState(false);
  const [demoPolicy, setDemoPolicy] = useState("demo:product-commander:MEDIUM:1"); const [demo, setDemo] = useState<CycleEvaluation | null>(null);
  const refresh = useCallback(async () => { try { setPolicies(await slaService.listPolicies()); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao carregar políticas."); } finally { setLoading(false); } }, []);
  useEffect(() => { void refresh(); return slaService.subscribe(() => void refresh()); }, [refresh]);
  async function save(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    try { await slaService.createPolicy(input); setOpen(false); notify("Rascunho de política criado. Revise antes de publicar."); await refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao salvar."); } finally { setBusy(false); }
  }
  async function publish(policy: SlaPolicyVersion) {
    setBusy(true); setError("");
    try { await slaService.publishPolicy(policy.id); notify("Política publicada para novos ciclos."); await refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao publicar."); } finally { setBusy(false); }
  }
  async function simulate(scenario: Parameters<typeof slaService.demoScenario>[1]) {
    try { setDemo(await slaService.demoScenario(demoPolicy, scenario)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha na demonstração."); }
  }
  return <AppShell><div className="mx-auto w-full max-w-6xl space-y-5"><PageHeading eyebrow="Administração" title="Políticas SLA" description="24x7 em minutos corridos. Publicações imutáveis; novas versões afetam somente novos ciclos." action={<button className="workspace-button-primary" onClick={() => { setInput(initial); setOpen(true); }}>Nova política</button>} />
    <p className="rounded-xl bg-[var(--accent-soft)] p-3 text-sm">Metas iniciais de 7Commander e 7Finance são dados fictícios de homologação. Não representam SLA comercial definitivo.</p>
    {loading && <p role="status">Carregando políticas...</p>}{error && <div role="alert" className="text-sm text-[var(--danger)]">{error} <button className="underline" onClick={() => void refresh()}>Tentar novamente</button></div>}
    <section aria-label="Histórico de políticas" className="grid gap-3 md:grid-cols-2">{[...policies].sort((a, b) => a.productId.localeCompare(b.productId) || a.priority.localeCompare(b.priority) || b.version - a.version).map(policy => <Card key={policy.id}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{products.find(product => product.id === policy.productId)?.displayName} · {priorityLabels[policy.priority]}</h3><span className="text-xs font-semibold">v{policy.version} · {policy.status === "PUBLISHED" ? "Publicada" : "Rascunho"}</span></div><dl className="mt-3 space-y-1 text-sm"><div>Primeira resposta: {policy.firstResponseMinutes} min</div><div>Resolução: {policy.resolutionMinutes} min</div><div>Pausa aguardando cliente: {policy.pauseResolutionWhileWaitingCustomer ? "Sim" : "Não"}</div><div>Publicação: {policy.publishedAt ? formatDate(policy.publishedAt) : "Ainda não publicada"}</div></dl><div className="mt-4 flex flex-wrap gap-2">{policy.status === "DRAFT" && <button className="workspace-button-primary" disabled={busy} onClick={() => void publish(policy)}>Publicar v{policy.version}</button>}<button className="workspace-button-secondary" disabled={busy} onClick={() => { setInput({ productId: policy.productId, priority: policy.priority, firstResponseMinutes: policy.firstResponseMinutes, resolutionMinutes: policy.resolutionMinutes, pauseResolutionWhileWaitingCustomer: policy.pauseResolutionWhileWaitingCustomer }); setOpen(true); }}>Criar nova versão</button></div><details className="mt-3 text-xs"><summary className="cursor-pointer">Auditoria</summary>{policy.audit.map((entry, index) => <p className="mt-1" key={index}>{entry.action === "CREATED" ? "Criada" : "Publicada"} · {formatDate(entry.at)} · {entry.actorUserId === "DEMO" ? "Dados demo" : "ADMIN"}</p>)}</details></Card>)}</section>
    <Card><section aria-label="Laboratório SLA" className="space-y-3"><h3 className="font-semibold">Laboratório de homologação</h3><p className="text-sm text-[var(--text-secondary)]">Relógio controlado em cenário isolado. Não altera chamados, políticas ou notificações. Os testes automatizados cobrem a entrega e a unicidade dos alertas reais locais.</p><label className="block text-sm font-medium">Política demonstrativa<select className="workspace-select mt-1" value={demoPolicy} onChange={event => { setDemoPolicy(event.target.value); setDemo(null); }}>{policies.filter(policy => policy.status === "PUBLISHED").map(policy => <option key={policy.id} value={policy.id}>{products.find(product => product.id === policy.productId)?.displayName} · {priorityLabels[policy.priority]} · v{policy.version}</option>)}</select></label><div className="flex flex-wrap gap-2">{([["BOUNDARY", "Limite exato"], ["BREACH", "Após o limite"], ["PAUSE", "Aguardando cliente"], ["RESOLVED", "Resolvida no prazo"], ["NO_REPLY", "Resolvida sem resposta"]] as const).map(([scenario, label]) => <button key={scenario} className="workspace-button-secondary" onClick={() => void simulate(scenario)}>{label}</button>)}</div>{demo && <div aria-live="polite" className="grid gap-3 sm:grid-cols-2">{(["firstResponse", "resolution"] as const).map(metric => <div key={metric} className="rounded-xl bg-[var(--bg-muted)] p-3 text-sm"><p className="mb-2 font-semibold">{metric === "firstResponse" ? "Primeira resposta" : "Resolução"}</p><SlaBadge state={demo[metric].state} /><p className="mt-2">{resultLabels[demo[metric].result]}</p><p>Tempo ativo: {demo[metric].activeElapsedMinutes?.toFixed(3)} min · Meta: {demo[metric].targetMinutes} min</p></div>)}</div>}</section></Card>
    <Drawer open={open} onClose={() => { if (!busy) setOpen(false); }} title="Nova versão de política"><form className="space-y-4" onSubmit={event => void save(event)}><p className="text-sm">Salve um rascunho e publique após revisar. A versão publicada não poderá ser editada.</p><label className="block text-sm font-medium">Produto<select className="workspace-select mt-1" value={input.productId} onChange={event => setInput({ ...input, productId: event.target.value })}>{products.map(product => <option key={product.id} value={product.id}>{product.displayName}</option>)}</select></label><label className="block text-sm font-medium">Prioridade<select className="workspace-select mt-1" value={input.priority} onChange={event => setInput({ ...input, priority: event.target.value as TicketPriority })}>{priorities.map(priority => <option key={priority} value={priority}>{priorityLabels[priority]}</option>)}</select></label>{([["firstResponseMinutes", "Primeira resposta (minutos)"], ["resolutionMinutes", "Resolução (minutos)"]] as const).map(([key, label]) => <label key={key} className="block text-sm font-medium">{label}<input className="workspace-input mt-1" type="number" min={1} max={5256000} step={1} required value={input[key]} onChange={event => setInput({ ...input, [key]: Number(event.target.value) })} /></label>)}<label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={input.pauseResolutionWhileWaitingCustomer} onChange={event => setInput({ ...input, pauseResolutionWhileWaitingCustomer: event.target.checked })} />Pausar resolução enquanto aguarda cliente</label>{error && <p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}<button className="workspace-button-primary" type="submit" disabled={busy}>{busy ? "Salvando..." : "Salvar rascunho"}</button></form></Drawer>
  </div></AppShell>;
}
export default function SlaPoliciesPage() { return <RequireAuth roles={["ADMIN"]}><Policies /></RequireAuth>; }
