"use client";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell } from "@/components/app/app-shell";
import { RequireAuth } from "@/features/auth/require-auth";
import { Card } from "@/components/ui/card";
import { PageHeading } from "@/components/tickets/ticket-ui";
import { ticketTypes, typeLabels, type TicketType } from "@/features/tickets/types";
import { localDateInterval, reportingService } from "@/services/reporting/service";
import type { ReportingResult, SlaCounts } from "@/services/reporting/types";
const number = (value: number | null) => value === null ? "Sem amostra" : value.toLocaleString("pt-BR", { maximumFractionDigits: 2 });
const percent = (value: number | null) => value === null ? "Sem amostra" : `${number(value * 100)}%`;
function Metrics({ title, caption, values }: { title: string; caption: string; values: [string, string | number][] }) { return <Card><h3 className="text-base font-semibold">{title}</h3><p className="mt-1 text-xs text-[var(--text-secondary)]">{caption}</p><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{values.map(([label, value]) => <div key={label} className="min-w-0"><dt className="text-xs text-[var(--text-secondary)]">{label}</dt><dd className="mt-1 break-words text-xl font-semibold">{value}</dd></div>)}</dl></Card>; }
function Reports() {
  const today = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };
  const [start, setStart] = useState(() => `${new Date().getFullYear()}-01-01`); const [end, setEnd] = useState(today);
  const [client, setClient] = useState(""); const [product, setProduct] = useState(""); const [type, setType] = useState<TicketType | "">("");
  const [options, setOptions] = useState<{ clients: [string, string][]; products: [string, string][] }>({ clients: [], products: [] });
  const [report, setReport] = useState<ReportingResult | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void reportingService.filterOptions().then(setOptions).catch(cause => setError(cause instanceof Error ? cause.message : "Falha nos filtros.")); }, []);
  async function load(event?: FormEvent) {
    event?.preventDefault(); setBusy(true); setError("");
    try { const interval = localDateInterval(start, end); setReport(await reportingService.query({ ...interval, clientId: client || undefined, productId: product || undefined, type: type || undefined })); }
    catch (cause) { setReport(null); setError(cause instanceof Error ? cause.message : "Falha ao consultar relatório."); }
    finally { setBusy(false); }
  }
  const slaValues = (data: SlaCounts): [string, string | number][] => [["MET", data.MET], ["NOT_MET", data.NOT_MET], ["PENDING", data.PENDING], ["NOT_CONFIGURED", data.NOT_CONFIGURED], ["INVALID_HISTORY", data.INVALID_HISTORY], ["Taxa no prazo", percent(data.metRate)], ["Denominador MET + NOT_MET", data.denominator]];
  return <AppShell><div className="mx-auto w-full max-w-6xl space-y-5"><PageHeading eyebrow="Operação interna" title="Relatórios" description="Indicadores derivados exclusivamente dos registros persistidos e autorizados." /><p className="rounded-xl bg-[var(--accent-soft)] p-3 text-sm">Dados locais de homologação. Estes números não representam dados de produção.</p><Card><form aria-label="Filtros dos relatórios" onSubmit={event => void load(event)} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm font-medium">Data inicial<input type="date" className="workspace-input mt-1" required value={start} onChange={event => setStart(event.target.value)} /></label><label className="text-sm font-medium">Data final<input type="date" className="workspace-input mt-1" required value={end} onChange={event => setEnd(event.target.value)} /></label><label className="text-sm font-medium">Cliente<select className="workspace-select mt-1" value={client} onChange={event => setClient(event.target.value)}><option value="">Todos</option>{options.clients.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label className="text-sm font-medium">Produto<select className="workspace-select mt-1" value={product} onChange={event => setProduct(event.target.value)}><option value="">Todos</option>{options.products.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label className="text-sm font-medium">Tipo<select className="workspace-select mt-1" value={type} onChange={event => setType(event.target.value as TicketType | "")}><option value="">Todos</option>{ticketTypes.map(value => <option key={value} value={value}>{typeLabels[value]}</option>)}</select></label><button className="workspace-button-primary self-end" type="submit" disabled={busy}>{busy ? "Consultando..." : "Consultar relatório"}</button></form></Card>{error && <div role="alert" className="text-sm text-[var(--danger)]">{error} <button className="underline" onClick={() => void load()}>Tentar novamente</button></div>}{busy && <p role="status">Lendo dados persistidos...</p>}
    {!report && !busy && !error && <p className="text-sm text-[var(--text-secondary)]">Escolha o período e consulte o relatório.</p>}
    {report && <section aria-label="Resultado dos relatórios" className="space-y-4"><Card><p className="text-sm">Intervalo utilizado em UTC: [{report.interval.start}, {report.interval.end})</p><p className="mt-1 text-xs text-[var(--text-secondary)]">Datas interpretadas no fuso do navegador: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Data final inclui o dia escolhido. Cada bloco informa sua própria coorte.</p></Card>
      <Metrics title="Volume" caption="Coorte por CREATED. Resoluções e reaberturas dos tickets criados no período, até o fim do intervalo." values={[["Tickets criados", report.volume.created], ["Tickets resolvidos distintos", report.volume.resolved], ["Tickets reabertos distintos", report.volume.reopenedTickets], ["Eventos REOPENED", report.volume.reopenedEvents], ["Taxa de reabertura", percent(report.volume.reopenRate)], ["Denominador: tickets resolvidos", report.volume.resolved]]} />
      <Metrics title="Atendimento" caption="Coorte por RESOLVED do ciclo. Tempos ativos em minutos; registros sem snapshot válido são excluídos." values={[["Ciclos concluídos", report.attendance.completedCycles], ["Média da primeira resposta (min)", number(report.attendance.firstResponse.mean)], ["Mediana da primeira resposta (min)", number(report.attendance.firstResponse.median)], ["Amostra de primeira resposta", report.attendance.firstResponse.count], ["Sem primeira resposta na amostra válida", report.attendance.missingFirstResponse], ["Média de resolução (min)", number(report.attendance.resolution.mean)], ["Mediana de resolução (min)", number(report.attendance.resolution.median)], ["Amostra de resolução", report.attendance.resolution.count], ["Excluídos da amostra", report.attendance.excluded], ["Sem configuração", report.attendance.notConfigured], ["Histórico inválido", report.attendance.invalidHistory], ["Resultado ainda pendente", report.attendance.pending]]} />
      <Metrics title="SLA: primeira resposta" caption="Coorte por RESOLVED. Taxa MET / (MET + NOT_MET); ausências e pendências fora do denominador." values={slaValues(report.sla.firstResponse)} /><Metrics title="SLA: resolução" caption="Coorte por RESOLVED. Resultados persistidos; a consulta não avalia nem reconcilia SLA." values={slaValues(report.sla.resolution)} />
      <Metrics title="Satisfação" caption="Coorte por submittedAt das avaliações recebidas. Rating ausente não entra na média." values={[["Avaliações recebidas", report.satisfaction.received], ["Sim", report.satisfaction.yes], ["Não", report.satisfaction.no], ["Taxa positiva SIM / (SIM + NÃO)", percent(report.satisfaction.positiveRate)], ["Rating médio", number(report.satisfaction.rating.mean)], ["Amostra de ratings", report.satisfaction.rating.count]]} />
      <Metrics title="Taxa de resposta" caption="Coorte das oportunidades por RESOLVED. Respostas recebidas até o fim do intervalo; canceladas por reabertura são excluídas. Este denominador difere da coorte submittedAt acima." values={[["Oportunidades elegíveis", report.satisfaction.opportunities], ["Respondidas na coorte", report.satisfaction.responsesInResolutionCohort], ["Taxa de resposta", percent(report.satisfaction.responseRate)], ["Canceladas pela reabertura", report.satisfaction.cancelled]]} />
      <Card><h3 className="font-semibold">Segmentação de volume</h3><div className="mt-3 grid gap-4 sm:grid-cols-3">{([["Cliente", report.segments.clients], ["Produto", report.segments.products], ["Tipo", report.segments.types]] as const).map(([label, items]) => <div key={label}><h4 className="text-sm font-semibold">{label}</h4>{items.length ? items.map(item => <p key={item.id} className="mt-1 text-sm">{item.label}: {item.count}</p>) : <p className="mt-1 text-sm">Sem dados neste período.</p>}</div>)}</div></Card>
    </section>}
  </div></AppShell>;
}
export default function ReportingPage() { return <RequireAuth roles={["SUPPORT", "ADMIN"]}><Reports /></RequireAuth>; }
