import Link from "next/link";
import { ArrowLeft, ArrowRight, Eye, PlusCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { ActionButton } from "@/components/ui/action-button";
import { Card } from "@/components/ui/card";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { Drawer } from "@/components/ui/drawer";
import { impactLabels, statusLabels, type Ticket, type TicketStatus } from "@/features/tickets/types";

export function formatDate(value: string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
const tones: Record<TicketStatus, "neutral" | "info" | "warning" | "success"> = { OPEN: "info", IN_PROGRESS: "info", WAITING_CUSTOMER: "warning", UNDER_ANALYSIS: "info", RESOLVED: "success", CLOSED: "neutral", REOPENED: "warning" };
export function StatusBadge({ status }: { status: TicketStatus }) { return <Badge tone={tones[status]}>{statusLabels[status]}</Badge>; }
export function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description?: string; action?: React.ReactNode }) { return <section className="page-hero flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="workspace-section-label text-[var(--accent)]">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold text-[var(--text-primary)]">{title}</h2>{description && <p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">{description}</p>}</div>{action}</section>; }
export function TicketFeedback({ loading, error, retry }: { loading: boolean; error: string | null; retry: () => void }) { if (loading) return <LoadingState />; if (!error) return null; return <div role="alert"><ErrorState /><p className="mt-2 text-sm text-[var(--danger)]">{error}</p><ActionButton label="Tentar novamente" icon={<ArrowRight size={16} />} onClick={retry} /></div>; }
export function NewTicketLink() { return <Link href="/tickets/new" className="workspace-button-primary"><PlusCircle size={18} />Novo chamado</Link>; }
export function BackLink({ href = "/tickets" }: { href?: string }) { return <Link href={href} className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--accent)]"><ArrowLeft size={16} />Voltar</Link>; }
export function TicketRow({ ticket, onQuickView }: { ticket: Ticket; onQuickView: (ticket: Ticket) => void }) { return <tr className="border-b border-[var(--border)] last:border-0 hover:bg-[var(--bg-muted)]"><td className="px-4 py-4 font-semibold text-[var(--accent)]"><Link href={`/tickets/${ticket.id}`} className="hover:underline">{ticket.publicCode}</Link></td><td className="px-4 py-4">{ticket.productNameSnapshot}</td><td className="max-w-[320px] truncate px-4 py-4">{ticket.subject}</td><td className="px-4 py-4"><StatusBadge status={ticket.status} /></td><td className="whitespace-nowrap px-4 py-4">{formatDate(ticket.updatedAt)}</td><td className="px-4 py-4"><ActionButton compact label={`Visualizar ${ticket.publicCode}`} icon={<Eye size={18} />} onClick={() => onQuickView(ticket)} /></td></tr>; }
export function TicketQuickView({ ticket, onClose }: { ticket: Ticket | null; onClose: () => void }) { return <Drawer open={Boolean(ticket)} onClose={onClose} title={ticket?.publicCode ?? "Chamado"}>{ticket && <div className="space-y-5"><div><p className="workspace-section-label">Assunto</p><h3 className="mt-1 text-lg font-semibold">{ticket.subject}</h3></div><div className="flex flex-wrap gap-2"><StatusBadge status={ticket.status} /><Badge>{ticket.productNameSnapshot}</Badge></div><dl className="grid gap-3 text-sm"><div><dt className="text-[var(--text-tertiary)]">Criado em</dt><dd>{formatDate(ticket.createdAt)}</dd></div><div><dt className="text-[var(--text-tertiary)]">Última atualização</dt><dd>{formatDate(ticket.updatedAt)}</dd></div><div><dt className="text-[var(--text-tertiary)]">Impacto</dt><dd>{impactLabels[ticket.impact]}</dd></div></dl><div><p className="workspace-section-label">Resumo</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[var(--text-secondary)]">{ticket.messages[0]?.body}</p></div><Link href={`/tickets/${ticket.id}`} onClick={onClose} className="workspace-button-primary">Abrir chamado completo <ArrowRight size={16} /></Link></div>}</Drawer>; }
export function RecentTickets({ tickets, onQuickView }: { tickets: Ticket[]; onQuickView: (ticket: Ticket) => void }) { return <div className="space-y-3">{tickets.map((ticket) => <Card key={ticket.id} className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/tickets/${ticket.id}`} className="font-semibold text-[var(--accent)] hover:underline">{ticket.publicCode}</Link><StatusBadge status={ticket.status} /></div><p className="mt-2 truncate text-sm font-medium">{ticket.subject}</p><p className="mt-1 text-xs text-[var(--text-secondary)]">{ticket.productNameSnapshot} · {formatDate(ticket.updatedAt)}</p></div><ActionButton compact label={`Visualizar ${ticket.publicCode}`} icon={<Eye size={18} />} onClick={() => onQuickView(ticket)} /></Card>)}</div>; }
